### ISSUE TITLE
"hello world" (ReproSchema for Dummies) instructions?

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/demo-protocol#21]
Unless I', missing something, while this repo has all the ingredients for standing up my own demo example, I'm missing some high level "how to" implement a version of this. I can customize my items and protocols, but how do I get my own little webpage to run?

I apologize if this is already there, was reading the entire ReproSchema system quickly, and was hoping to get to the my own demo capability, which is really cool and inspiring!

**Comment by danielmlow** [comment]
@dnkennedy @satra [here](https://docs.google.com/document/d/1VFqzdYYc3sfsdQ43JdJZVO83yH8hBBIwaYuAqAl8SaE/edit?usp=sharing) is a document we set up including some video demos. Let me know if you get stuck

**Comment by Remi-Gau** [comment]
I think there might be a partially baked version of what you are looking for in this PR (that has been WIP for more than a year... sob)

https://github.com/ReproNim/reproschema/pull/399

**Comment by satra** [comment]
closing this in favor of changes in the reproschema repo.
