### ISSUE TITLE
automatical updates on reproschema version

### ISSUE THREAD

**Issue by yibeichan** [ReproNim/demo-protocol#24]
Hi @djarecka 
currently, the reproschema version in our demo-protocol is outdated. Our latest version is `1.0.0-rc4`, but the demo has `1.0.0-rc2`. We probably want to keep the version updated in this demo protocol all the time.
https://github.com/ReproNim/demo-protocol/blob/16a54ef5eeaef7282d9ed0410cc22ff1bfef6e71/DemoProtocol/DemoProtocol_schema#L2-L11

Is it possible that we set up some checks/tests in GA that automatically update the `@context` and `schemaVersion` lines in each schema? For example, something related to validation?
https://github.com/ReproNim/demo-protocol/blob/16a54ef5eeaef7282d9ed0410cc22ff1bfef6e71/.github/workflows/build_deploy.yml#L49-L52

If it's doable, I can start working on it.

**Comment by Remi-Gau** [comment]
from the top of my head, have a script that checks that the version used in the protocol matches the latest release of the schema, then we run the script at regular interval with a CRON job via github action

**Comment by yibeichan** [comment]
@Remi-Gau that sounds exactly what we want. but this script is not in this demo-protocol repo. not in reproschema repo either. here are all three scripts https://github.com/ReproNim/reproschema/tree/master/scripts
also not in reproschema-py repo https://github.com/ReproNim/reproschema-py/tree/master
did I miss somewhere else?

**Comment by Remi-Gau** [comment]
oh sorry I was unclear: that script only exists as a concept in my head at the moment.

it would have to be written first

**Comment by yibeichan** [comment]
lol i probably saw the email too early in the morning and misunderstood it. sounds good, let's see whether I can bring what in your head to code.

**Comment by yibeichan** [comment]
okay, chatgpt helped me write this https://github.com/ReproNim/reproschema-protocol-cookiecutter/blob/main/.github/workflows/autoupdate_schema_version.yaml
achieved our goal haha. closing the issue now

**Comment by Remi-Gau** [comment]
Nice
Just had a look. May have a couple of tiny suggestions. I may open a pr and let you decide.
