### ISSUE TITLE
"create" a dummy activity with all the supported input / widget type

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/demo-protocol#4]
We discussed with @sanuann the possibiliy of creating a dummy acticity that would contain all the input types the schema / UI support.

I suspect this could help with:
- testing some the apps (like the UI) but also potential other implementation,
- could be used to show users the UI what each widget looks like.

Would this repo be the right place to create such activity?

**Comment by satra** [comment]
the default protocol should indeed reflect the capabilities more than a study we were planning :)
